### ISSUE TITLE
单机多gpu训练只用一块卡

### ISSUE THREAD

**Issue by renjunxiang** [zjcanjux/daguan_ner_Bert_bilstm_crf#1]
你好，我尝试训练bert，1080ti*4。不管怎么设置，都只用了第一块gpu，另外三块的显存占用基本只有100M。我调大batchsize=64后就会OOM，请问您有这种情况吗？和代码里面用的TPU优化器有关吗？谢谢！

**Comment by zjcanjux** [comment]
> 你好，我尝试训练bert，1080ti*4。不管怎么设置，都只用了第一块gpu，另外三块的显存占用基本只有100M。我调大batchsize=64后就会OOM，请问您有这种情况吗？和代码里面用的TPU优化器有关吗？谢谢！

我是用一块1080ti跑的，你四块，估计是你多卡设置有问题，所以没用起来。

**Comment by renjunxiang** [comment]
谢谢你的回复，我指定单卡可以并行训练四个，但是没办法分布式训练一个。
