### ISSUE TITLE
你好 请问可以探讨交流一下这个比赛吗

### ISSUE THREAD

**Issue by neverstoplearn** [zjcanjux/daguan_ner_Bert_bilstm_crf#2]

**Comment by neverstoplearn** [comment]
请问你给出的百度云链接里面bert模型最好的是哪一个

**Comment by zjcanjux** [comment]
> 请问你给出的百度云链接里面bert模型最好的是哪一个

目前就my_bert 文件夹里的那个

**Comment by neverstoplearn** [comment]
> > 请问你给出的百度云链接里面bert模型最好的是哪一个
> 
> 目前就my_bert 文件夹里的那个

这个模型单模大概可以到多少  另外你对NER的模型融合的话有什么想法吗？我单模目前92.1 想进行模型融合 之前没用做过nlp的  大佬有什么想法吗

**Comment by zjcanjux** [comment]
> > > 请问你给出的百度云链接里面bert模型最好的是哪一个
> > 
> > 
> > 目前就my_bert 文件夹里的那个
> 
> 这个模型单模大概可以到多少 另外你对NER的模型融合的话有什么想法吗？我单模目前92.1 想进行模型融合 之前没用做过nlp的 大佬有什么想法吗

我现在91.8，你用bert了么？

**Comment by neverstoplearn** [comment]
> > > > 请问你给出的百度云链接里面bert模型最好的是哪一个
> > > 
> > > 
> > > 目前就my_bert 文件夹里的那个
> > 
> > 
> > 这个模型单模大概可以到多少 另外你对NER的模型融合的话有什么想法吗？我单模目前92.1 想进行模型融合 之前没用做过nlp的 大佬有什么想法吗
> 
> 我现在91.8，你用bert了么？

是的  bert

**Comment by neverstoplearn** [comment]
> > > > > 请问你给出的百度云链接里面bert模型最好的是哪一个
> > > > 
> > > > 
> > > > 目前就my_bert 文件夹里的那个
> > > 
> > > 
> > > 这个模型单模大概可以到多少 另外你对NER的模型融合的话有什么想法吗？我单模目前92.1 想进行模型融合 之前没用做过nlp的 大佬有什么想法吗
> > 
> > 
> > 我现在91.8，你用bert了么？
> 
> 是的 bert

就是你开源的现在这个模型是吗

**Comment by neverstoplearn** [comment]
你之前有做过这方面的模型融合吗

**Comment by zjcanjux** [comment]
> 你之前有做过这方面的模型融合吗

做过，但这种90多的模型，互相融合，效果提升很有限，按我以前的经验来看。

**Comment by neverstoplearn** [comment]
大概千分点 难受

**Comment by FreeFlyXiaoMa** [comment]
大佬想问下，直接用官方提供的脱敏数据，训练时会提供token长度不一致，你是怎么解决的呢

**Comment by zjcanjux** [comment]
> 大佬想问下，直接用官方提供的脱敏数据，训练时会提供token长度不一致，你是怎么解决的呢

是每个句子长度不一致么？需要通过pad，将一个batch里的句子，长度补齐。

**Comment by FreeFlyXiaoMa** [comment]
> > 大佬想问下，直接用官方提供的脱敏数据，训练时会提供token长度不一致，你是怎么解决的呢
> 
> 是每个句子长度不一致么？需要通过pad，将一个batch里的句子，长度补齐。

是的，送进bert模型中的token长度不一致

**Comment by dengkunn** [comment]
> > > > 请问你给出的百度云链接里面bert模型最好的是哪一个
> > > 
> > > 
> > > 目前就my_bert 文件夹里的那个
> > 
> > 
> > 这个模型单模大概可以到多少 另外你对NER的模型融合的话有什么想法吗？我单模目前92.1 想进行模型融合 之前没用做过nlp的 大佬有什么想法吗
> 
> 我现在91.8，你用bert了么？



> > 你之前有做过这方面的模型融合吗
> 
> 做过，但这种90多的模型，互相融合，效果提升很有限，按我以前的经验来看。

大佬，请教一下：我直接用你的这个模型跑了一下（没做任何改变），预训练的也是你网盘提供的，大概８到９个epoch之后f1 score就不在dev上提高了；submit 之后的结果为：81.3；和你提到的91.8差距还是太大了；根据你的经验是哪里出问题了？学习率还是预训练的文件上还是说生成的结果文件处理上？其实我自己之前找了一个keras的模型改了一下，也是自己预训练模型（网络参数减少为1/4,单任务MLM的预训练），提交结果也只有80.1；一直不知道哪里出问题了，特请教一下；谢谢！
![Screenshot from 2019-08-30 21-53-10](https://user-images.githubusercontent.com/34706567/64026053-99e1d280-cb70-11e9-87e0-942bd988363d.png)

**Comment by zjcanjux** [comment]
> > > > > 请问你给出的百度云链接里面bert模型最好的是哪一个
> > > > 
> > > > 
> > > > 目前就my_bert 文件夹里的那个
> > > 
> > > 
> > > 这个模型单模大概可以到多少 另外你对NER的模型融合的话有什么想法吗？我单模目前92.1 想进行模型融合 之前没用做过nlp的 大佬有什么想法吗
> > 
> > 
> > 我现在91.8，你用bert了么？
> 
> > > 你之前有做过这方面的模型融合吗
> > 
> > 
> > 做过，但这种90多的模型，互相融合，效果提升很有限，按我以前的经验来看。
> 
> 大佬，请教一下：我直接用你的这个模型跑了一下（没做任何改变），预训练的也是你网盘提供的，大概８到９个epoch之后f1 score就不在dev上提高了；submit 之后的结果为：81.3；和你提到的91.8差距还是太大了；根据你的经验是哪里出问题了？学习率还是预训练的文件上还是说生成的结果文件处理上？其实我自己之前找了一个keras的模型改了一下，也是自己预训练模型（网络参数减少为1/4,单任务MLM的预训练），提交结果也只有80.1；一直不知道哪里出问题了，特请教一下；谢谢！
> ![Screenshot from 2019-08-30 21-53-10](https://user-images.githubusercontent.com/34706567/64026053-99e1d280-cb70-11e9-87e0-942bd988363d.png)

会波动的，再差也不会是81，再dev上86的时候，test上不会是81
